version: '3'
services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo_list_db
    ports:
      - "5432:5432"
      - "8080:8080"
    volumes:
      - db-data:/var/lib/postgresql/data
  app:
    image: todo_app:latest
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: todo_list_db
      DB_USER: postgres
      DB_PASSWORD: postgres
    network_mode:
      service:db
volumes:
  db-data: